📦
379 /agent/index.js.map
139 /agent/index.js
2258 /agent/process.js.map
1564 /agent/process.js
✄
{"version":3,"file":"index.js","names":["memory","console","log","variable","rpc","exports","readVariable","writeVariable","my_number"],"sourceRoot":"C:/Users/lucho/Documents/fridheat-engine/core/agent/","sources":["index.ts"],"mappings":"iBAASA,MAAc,eACvBC,QAAQC,IAAI,oBAgBZ,IAAIC,EAAmB,EAEvBC,IAAIC,QAAU,IACPL,EACHM,aAAc,IAAuBH,EACrCI,cAAgBC,IAAwBL,EAAWK,CAAS","ignoreList":[]}
✄
import{memory as r}from"./process.js";console.log("printing results");let e=5;rpc.exports={...r,readVariable:()=>e,writeVariable:r=>{e=r}};
✄
{"version":3,"file":"process.js","names":["MemoryPage","constructor","rangeDetails","isEnabled","this","enabled","toggleEnabled","setEnabled","getFileName","file_path","file","path","getBase","base","getSize","size","displayConfig","console","log","protection","MemoryPages","memoryPages","Process","enumerateRanges","forEach","range","push","filterByFilename","file_name","memoryPage","includes","filterByMemoryRange","init_memory","end_memory","inicioDecimal","parseInt","finDecimal","baseDecimal","toString","resetActiveMemoryPages","getValidPages","filter","getAllPages","displayAllMemoryPages","memory_pages","memory","startMemoryPages","restartMemoryPages","resetVisibilityMemoryPages","getAllMemoryPages","getActiveMemoryPages","filterByFileName"],"sourceRoot":"C:/Users/lucho/Documents/fridheat-engine/core/agent/","sources":["process.ts"],"mappings":"OAAM,MAAOA,WAITC,YAAYC,EAA4BC,GACpCC,KAAKF,aAAeA,EACpBE,KAAKC,QAAUF,CACnB,CAGOG,gBACHF,KAAKC,SAAWD,KAAKC,OACzB,CAEOE,WAAWF,GACdD,KAAKC,QAAUA,CACnB,CAEOF,YACH,OAAOC,KAAKC,OAChB,CACOG,cACH,IAAIC,EAAY,GAIhB,OAHIL,KAAKF,aAAaQ,MAAMC,OACxBF,EAAYL,KAAKF,aAAaQ,KAAKC,MAEhCF,CACX,CAEOG,UACH,OAAOR,KAAKF,aAAaW,IAC7B,CAEAC,UACI,OAAOV,KAAKF,aAAaa,IAC7B,CAGAC,gBAEIC,QAAQC,IAAI,WAAWd,KAAKI,mBAAmBJ,KAAKF,aAAaW,UAAUT,KAAKF,aAAaa,UAAUX,KAAKF,aAAaiB,yBAAyBf,KAAKC,UAC3J,SAGE,MAAOe,YAITnB,cAFQG,KAAAiB,YAA4B,GAGHC,QAAQC,gBAAgB,OAE9CC,SAASC,IACZrB,KAAKiB,YAAYK,KAAK,IAAI1B,WAAWyB,GAAO,GAAM,GAE1D,CAGOE,iBAAiBC,GAEpBxB,KAAKiB,YAAYG,SAASK,IAEtBA,EAAWtB,WAAWsB,EAAWrB,cAAcsB,SAASF,GAAW,GAE3E,CAGOG,oBAAoBC,EAAqBC,GAC5C,MAAMC,EAAgBC,SAASH,EAAa,IACtCI,EAAaD,SAASF,EAAY,IAExC7B,KAAKiB,YAAYG,SAASK,IACtB,MAAMQ,EAAcF,SAASN,EAAWjB,UAAU0B,WAAY,IAC9DT,EAAWtB,WAAW8B,GAAeH,GAAiBG,GAAeD,EAAW,GAExF,CAEOG,yBACHnC,KAAKiB,YAAYG,SAASK,IACtBA,EAAWtB,YAAW,EAAK,GAEnC,CAEOiC,gBACH,OAAOpC,KAAKiB,YAAYoB,QAAOZ,GACpBA,EAAW1B,aAE1B,CAEOuC,cACH,OAAOtC,KAAKiB,WAChB,CACOsB,wBACHvC,KAAKiB,YAAYG,SAASK,IACtBA,EAAWb,eAAe,GAElC,EAGJ,IAAI4B,EAAmC,YAEhC,MAAMC,OAAS,CAElBC,iBAAkB,KACdF,EAAe,IAAIxB,WAAa,EAEpC2B,mBAAoB,KAChBH,EAAe,IAAIxB,WAAa,EAEpC4B,2BAA4B,KACxBJ,GAAcL,wBAAwB,EAE1CU,kBAAmB,IACRL,GAAcF,cAEzBQ,qBAAsB,IACXN,GAAcJ,gBAEzBW,iBAAmBvB,IACfgB,GAAcjB,iBAAiBC,EAAU,EAE7CG,oBAAqB,CAACC,EAAqBC,KACvCW,GAAcb,oBAAoBC,EAAaC,EAAW","ignoreList":[]}
✄
export class MemoryPage{constructor(e,t){this.rangeDetails=e,this.enabled=t}toggleEnabled(){this.enabled=!this.enabled}setEnabled(e){this.enabled=e}isEnabled(){return this.enabled}getFileName(){let e="";return this.rangeDetails.file?.path&&(e=this.rangeDetails.file.path),e}getBase(){return this.rangeDetails.base}getSize(){return this.rangeDetails.size}displayConfig(){console.log(`Range: [${this.getFileName()} - ${this.rangeDetails.base} - ${this.rangeDetails.size} - ${this.rangeDetails.protection}], Enabled: ${this.enabled}`)}}export class MemoryPages{constructor(){this.memoryPages=[],Process.enumerateRanges("r--").forEach((e=>{this.memoryPages.push(new MemoryPage(e,!0))}))}filterByFilename(e){this.memoryPages.forEach((t=>{t.setEnabled(t.getFileName().includes(e))}))}filterByMemoryRange(e,t){const s=parseInt(e,16),a=parseInt(t,16);this.memoryPages.forEach((e=>{const t=parseInt(e.getBase().toString(),16);e.setEnabled(t>=s&&t<=a)}))}resetActiveMemoryPages(){this.memoryPages.forEach((e=>{e.setEnabled(!0)}))}getValidPages(){return this.memoryPages.filter((e=>e.isEnabled()))}getAllPages(){return this.memoryPages}displayAllMemoryPages(){this.memoryPages.forEach((e=>{e.displayConfig()}))}}let e=null;export const memory={startMemoryPages:()=>{e=new MemoryPages},restartMemoryPages:()=>{e=new MemoryPages},resetVisibilityMemoryPages:()=>{e?.resetActiveMemoryPages()},getAllMemoryPages:()=>e?.getAllPages(),getActiveMemoryPages:()=>e?.getValidPages(),filterByFileName:t=>{e?.filterByFilename(t)},filterByMemoryRange:(t,s)=>{e?.filterByMemoryRange(t,s)}};