📦
393 /agent/index.js.map
130 /agent/index.js
1691 /agent/process.js.map
1088 /agent/process.js
✄
{"version":3,"file":"index.js","names":["console","log","variable","rpc","exports","readVariable","writeVariable","my_number"],"sourceRoot":"/Users/cesarrodriguez/Documents/advanced-android/fridheat-engine/core/agent/","sources":["index.ts"],"mappings":"AACAA,QAAQC,IAAI,oBAgBZ,IAAIC,EAAmB,EAEvBC,IAAIC,QAAU,CACVC,aAAc,IAAuBH,EACrCI,cAAgBC,IAAwBL,EAAWK,CAAS,GAEhEP,QAAQC,IAAI","ignoreList":[]}
✄
console.log("printing results");let e=5;rpc.exports={readVariable:()=>e,writeVariable:r=>{e=r}},console.log("termino 5");export{};
✄
{"version":3,"file":"process.js","names":["MemoryPage","constructor","rangeDetails","isEnabled","this","enabled","toggleEnabled","setEnabled","getFileName","file_path","file","path","getBase","base","getSize","size","displayConfig","console","log","protection","MemoryPages","memoryPages","Process","enumerateRanges","forEach","range","push","filterByFilename","file_name","memoryPage","includes","filterByMemoryRange","init_memory","end_memory","inicioDecimal","parseInt","finDecimal","baseDecimal","toString","getValidPages","filter","displayAllMemoryPages"],"sourceRoot":"/Users/cesarrodriguez/Documents/advanced-android/fridheat-engine/core/agent/","sources":["process.ts"],"mappings":"OAAM,MAAOA,WAITC,YAAYC,EAA4BC,GACpCC,KAAKF,aAAeA,EACpBE,KAAKC,QAAUF,CACnB,CAGOG,gBACHF,KAAKC,SAAWD,KAAKC,OACzB,CAEOE,WAAWF,GACdD,KAAKC,QAAUA,CACnB,CAEOF,YACH,OAAOC,KAAKC,OAChB,CACOG,cACH,IAAIC,EAAY,GAIhB,OAHIL,KAAKF,aAAaQ,MAAMC,OACxBF,EAAYL,KAAKF,aAAaQ,KAAKC,MAEhCF,CACX,CAEOG,UACH,OAAOR,KAAKF,aAAaW,IAC7B,CAEAC,UACI,OAAOV,KAAKF,aAAaa,IAC7B,CAGAC,gBAEIC,QAAQC,IAAI,WAAWd,KAAKI,mBAAmBJ,KAAKF,aAAaW,UAAUT,KAAKF,aAAaa,UAAUX,KAAKF,aAAaiB,yBAAyBf,KAAKC,UAC3J,SAGE,MAAOe,YAITnB,cAFQG,KAAAiB,YAA4B,GAGHC,QAAQC,gBAAgB,OAE9CC,SAASC,IACZrB,KAAKiB,YAAYK,KAAK,IAAI1B,WAAWyB,GAAO,GAAM,GAE1D,CAGOE,iBAAiBC,GAEpBxB,KAAKiB,YAAYG,SAASK,IAEtBA,EAAWtB,WAAWsB,EAAWrB,cAAcsB,SAASF,GAAW,GAE3E,CAGOG,oBAAoBC,EAAqBC,GAC5C,MAAMC,EAAgBC,SAASH,EAAa,IACtCI,EAAaD,SAASF,EAAY,IAExC7B,KAAKiB,YAAYG,SAASK,IACtB,MAAMQ,EAAcF,SAASN,EAAWjB,UAAU0B,WAAY,IAC9DT,EAAWtB,WAAW8B,GAAeH,GAAiBG,GAAeD,EAAW,GAExF,CAEOG,gBACH,OAAOnC,KAAKiB,YAAYmB,QAAOX,GACpBA,EAAW1B,aAE1B,CAEOsC,wBACHrC,KAAKiB,YAAYG,SAASK,IACtBA,EAAWb,eAAe,GAElC","ignoreList":[]}
✄
export class MemoryPage{constructor(e,s){this.rangeDetails=e,this.enabled=s}toggleEnabled(){this.enabled=!this.enabled}setEnabled(e){this.enabled=e}isEnabled(){return this.enabled}getFileName(){let e="";return this.rangeDetails.file?.path&&(e=this.rangeDetails.file.path),e}getBase(){return this.rangeDetails.base}getSize(){return this.rangeDetails.size}displayConfig(){console.log(`Range: [${this.getFileName()} - ${this.rangeDetails.base} - ${this.rangeDetails.size} - ${this.rangeDetails.protection}], Enabled: ${this.enabled}`)}}export class MemoryPages{constructor(){this.memoryPages=[],Process.enumerateRanges("r--").forEach((e=>{this.memoryPages.push(new MemoryPage(e,!0))}))}filterByFilename(e){this.memoryPages.forEach((s=>{s.setEnabled(s.getFileName().includes(e))}))}filterByMemoryRange(e,s){const a=parseInt(e,16),t=parseInt(s,16);this.memoryPages.forEach((e=>{const s=parseInt(e.getBase().toString(),16);e.setEnabled(s>=a&&s<=t)}))}getValidPages(){return this.memoryPages.filter((e=>e.isEnabled()))}displayAllMemoryPages(){this.memoryPages.forEach((e=>{e.displayConfig()}))}}